language: generic

sudo: required

install:
  - sudo apt-get update
  - sudo add-apt-repository --yes ppa:eugenesan/ppa
  - sudo apt-get update
  - sudo apt-get install -y brotli
script:
  - bash -x main.sh