language: generic

sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install -y wget cmake
  - wget https://github.com/google/brotli/archive/v1.0.4.tar.gz
  - tar zxvf v1.0.4.tar.gz
  - cd brotli-1.0.4
  - cmake .
  - make
  - sudo cp ./brotli /bin
script:
  - bash -x main.sh