language: generic

sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install -y wget cmake
  - wget https://github.com/google/brotli/archive/v1.0.4.tar.gz
  - tar zxvf v1.0.4.tar.gz
  - cd brotli-1.0.4
  - cmake .
  - make
  - sudo cp ./brotli /bin
  - git config --global user.email "guzmansalv@gmail.com"
  - git config --global user.name "Salvador Guzman"
  - git clone 'https://github.com/sguzman/fresh-pages-snapshot'
  - cd ./fresh-pages-snapshot/
  - for i in *.txt.brotli; do cat ${i} | brotli -d; done | brotli > ./pages.brotli
  - git add pages.brotli
  - git commit -m 'Added snapshot'
  - git remote set-url origin ${PASS}
  - git push
script:
  - echo 'done'